server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: iot-service

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never

logging:
  level:
    com.ceygreen.iot: ${LOG_LEVEL:INFO}
