-- DISEASES
INSERT INTO diseases (name, normalized_name, description) VALUES
('Tomato Bacterial Spot', 'tomato bacterial spot', 'Bacterial infection causing dark water-soaked spots on leaves and fruit.'),
('Tomato Early Blight', 'tomato early blight', 'Fungal disease (Alternaria solani) causing concentric-ringed brown leaf spots.'),
('Tomato Late Blight', 'tomato late blight', 'Aggressive oomycete disease (Phytophthora infestans) causing rapid foliage collapse.'),
('Tomato Leaf Mold', 'tomato leaf mold', 'Fungal disease favoring high humidity; yellow spots on top of leaves, mold underneath.'),
('Tomato Septoria Leaf Spot', 'tomato septoria leaf spot', 'Fungal disease causing small circular spots with dark borders and grey centers.'),
('Tomato Spider Mites', 'tomato spider mites', 'Pest infestation (Tetranychus urticae) causing stippled, bronzed leaves.'),
('Tomato Target Spot', 'tomato target spot', 'Fungal disease (Corynespora cassiicola) causing concentric brown lesions.'),
('Tomato Yellow Leaf Curl Virus', 'tomato yellow leaf curl virus', 'Whitefly-transmitted viral disease causing leaf curling and stunting.'),
('Tomato Mosaic Virus', 'tomato mosaic virus', 'Viral disease causing mottled, distorted leaves; no chemical cure.'),
('Potato Early Blight', 'potato early blight', 'Fungal disease (Alternaria solani) similar presentation to tomato early blight.'),
('Potato Late Blight', 'potato late blight', 'Oomycete disease (Phytophthora infestans); historically devastating to potato crops.'),
('Pepper Bacterial Spot', 'pepper bacterial spot', 'Bacterial disease causing lesions on leaves, stems, and fruit.'),
('Chili Anthracnose', 'chili anthracnose', 'Fungal disease causing sunken, dark fruit lesions; major post-harvest loss cause.'),
('Chili Leaf Curl Virus', 'chili leaf curl virus', 'Whitefly-transmitted viral disease causing upward leaf curling and stunting.'),
('Pepper Powdery Mildew', 'pepper powdery mildew', 'Fungal disease presenting as white powdery growth on leaf surfaces.'),
('Strawberry Leaf Scorch', 'strawberry leaf scorch', 'Fungal disease causing purplish blotches that merge into scorched-looking leaves.'),
('Strawberry Gray Mold', 'strawberry gray mold', 'Botrytis cinerea infection causing fruit and blossom rot in humid conditions.'),
('Strawberry Powdery Mildew', 'strawberry powdery mildew', 'Fungal disease causing white powdery patches on leaves and fruit.'),
('Grape Black Rot', 'grape black rot', 'Fungal disease causing circular brown leaf lesions and shriveled, mummified fruit.'),
('Grape Esca', 'grape esca', 'Complex fungal trunk disease (Black Measles); no effective curative fungicide.'),
('Grape Leaf Blight', 'grape leaf blight', 'Fungal disease (Isariopsis leaf spot) causing angular brown leaf lesions.');

-- TREATMENTS
INSERT INTO treatments (disease_id, product_name, type, dosage, frequency, safety_notes, crop_type, severity, active) VALUES
((SELECT id FROM diseases WHERE normalized_name = 'tomato bacterial spot'), 'Copper Oxychloride', 'CHEMICAL', '2g/L water', 'Every 7 days', 'Avoid spraying during flowering; wear gloves.', 'Tomato', 'MODERATE', true),
((SELECT id FROM diseases WHERE normalized_name = 'tomato early blight'), 'Mancozeb 80% WP', 'CHEMICAL', '20g/10L water', 'Every 7 days', 'Do not harvest within 7 days of spraying.', 'Tomato', 'MODERATE', true),
((SELECT id FROM diseases WHERE normalized_name = 'tomato late blight'), 'Metalaxyl 8% + Mancozeb 64% WP', 'CHEMICAL', '12.5g/10L water', 'Every 7 days', 'Apply at first sign of disease; systemic + protectant combination.', 'Tomato', 'SEVERE', true),
((SELECT id FROM diseases WHERE normalized_name = 'tomato leaf mold'), 'Chlorothalonil', 'CHEMICAL', '2g/L water', 'Every 7-10 days', 'Ensure good ventilation in greenhouse to reduce humidity.', 'Tomato', 'MILD', true),
((SELECT id FROM diseases WHERE normalized_name = 'tomato septoria leaf spot'), 'Mancozeb 80% WP', 'CHEMICAL', '20g/10L water', 'Every 7 days', 'Remove and destroy infected lower leaves before spraying.', 'Tomato', 'MODERATE', true),
((SELECT id FROM diseases WHERE normalized_name = 'tomato spider mites'), 'Neem Oil', 'ORGANIC', '5ml/L water', 'Every 5 days', 'Spray in early morning or evening to avoid leaf burn.', 'Tomato', 'MILD', true),
((SELECT id FROM diseases WHERE normalized_name = 'tomato target spot'), 'Azoxystrobin', 'CHEMICAL', '10ml/10L water', 'Every 10 days', 'Rotate with a different fungicide class to prevent resistance.', 'Tomato', 'MODERATE', true),
((SELECT id FROM diseases WHERE normalized_name = 'tomato yellow leaf curl virus'), 'Imidacloprid (whitefly vector control)', 'CHEMICAL', '0.5ml/L water', 'Every 10 days', 'No direct cure; controls the whitefly vector, not the virus itself.', 'Tomato', 'SEVERE', true),
((SELECT id FROM diseases WHERE normalized_name = 'tomato mosaic virus'), 'Remove and destroy infected plants; sanitize tools', 'ORGANIC', 'N/A', 'As needed', 'No chemical cure exists; prevent spread via handling and tools.', 'Tomato', 'SEVERE', true),
((SELECT id FROM diseases WHERE normalized_name = 'potato early blight'), 'Mancozeb 80% WP', 'CHEMICAL', '20g/10L water', 'Every 7-10 days', 'Begin applications before symptoms appear in high-risk seasons.', 'Potato', 'MODERATE', true),
((SELECT id FROM diseases WHERE normalized_name = 'potato late blight'), 'Metalaxyl + Mancozeb', 'CHEMICAL', '12.5g/10L water', 'Every 7 days', 'Destroy cull piles and volunteer plants to reduce inoculum.', 'Potato', 'SEVERE', true),
((SELECT id FROM diseases WHERE normalized_name = 'pepper bacterial spot'), 'Copper Oxychloride', 'CHEMICAL', '3g/L water', 'Every 7 days', 'Avoid overhead irrigation which spreads bacterial spores.', 'Pepper', 'MODERATE', true),
((SELECT id FROM diseases WHERE normalized_name = 'chili anthracnose'), 'Mancozeb / Copper Oxychloride', 'CHEMICAL', '20g/10L water', 'Every 7 days', 'Remove and destroy infected fruit to reduce spread.', 'Chili', 'MODERATE', true),
((SELECT id FROM diseases WHERE normalized_name = 'chili leaf curl virus'), 'Imidacloprid (whitefly vector control)', 'CHEMICAL', '0.5ml/L water', 'Every 10 days', 'No direct cure; targets the whitefly vector.', 'Chili', 'SEVERE', true),
((SELECT id FROM diseases WHERE normalized_name = 'pepper powdery mildew'), 'Wettable Sulphur', 'ORGANIC', '20g/10L water', 'Every 7 days', 'Do not apply in high temperatures (above 32C) to avoid leaf scorch.', 'Pepper', 'MILD', true),
((SELECT id FROM diseases WHERE normalized_name = 'strawberry leaf scorch'), 'Captan 50% WP', 'CHEMICAL', '20g/10L water', 'Every 10 days', 'Apply preventively before wet, humid periods.', 'Strawberry', 'MODERATE', true),
((SELECT id FROM diseases WHERE normalized_name = 'strawberry gray mold'), 'Captan / Iprodione', 'CHEMICAL', '15g/10L water', 'Every 7 days', 'Improve air circulation between plants to reduce humidity.', 'Strawberry', 'SEVERE', true),
((SELECT id FROM diseases WHERE normalized_name = 'strawberry powdery mildew'), 'Wettable Sulphur', 'ORGANIC', '20g/10L water', 'Every 7 days', 'Avoid application during peak heat hours.', 'Strawberry', 'MILD', true),
((SELECT id FROM diseases WHERE normalized_name = 'grape black rot'), 'Mancozeb 80% WP', 'CHEMICAL', '20g/10L water', 'Every 10 days', 'Remove mummified fruit from vines and ground.', 'Grape', 'MODERATE', true),
((SELECT id FROM diseases WHERE normalized_name = 'grape esca'), 'Prune and destroy infected wood', 'ORGANIC', 'N/A', 'As needed', 'No effective curative fungicide exists; sanitation is the main control.', 'Grape', 'SEVERE', true),
((SELECT id FROM diseases WHERE normalized_name = 'grape leaf blight'), 'Mancozeb 80% WP', 'CHEMICAL', '20g/10L water', 'Every 10 days', 'Ensure good canopy airflow to reduce leaf wetness duration.', 'Grape', 'MODERATE', true);