import React, { useState, useEffect } from 'react';
import { useParams, Link, useNavigate } from 'react-router-dom';
import { useToast } from '../context/ToastContext';
import { getDiagnosis, deleteDiagnosis, resolveDiagnosisImageUrl } from '../api/diagnosis';
import { Diagnosis } from '../types/diagnosis';
import { getDiseaseDetail, DiseaseDetail } from '../data/diseaseKnowledge';
import { generateGeminiAgronomistReport, getStoredGeminiKey } from '../api/gemini';
import { IconLeaf, IconScan, IconShield, IconDrop, IconThermo, IconTrash, IconAlertTriangle } from '../components/icons/Icons';
import './ScanDetailPage.css';

export const ScanDetailPage: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { showToast } = useToast();

  const [diagnosis, setDiagnosis] = useState<Diagnosis | null>(null);
  const [diseaseDetail, setDiseaseDetail] = useState<DiseaseDetail | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Deletion modal state
  const [showDeleteModal, setShowDeleteModal] = useState(false);
  const [isDeleting, setIsDeleting] = useState(false);

  // Tab & AI Plan state
  const [activeTab, setActiveTab] = useState<'overview' | 'pathology' | 'treatment' | 'aiPlan'>('overview');
  const [aiReport, setAiReport] = useState<string | null>(null);
  const [loadingAi, setLoadingAi] = useState(false);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (!id) return;
    const fetchDetail = async () => {
      setLoading(true);
      setError(null);
      try {
        const data = await getDiagnosis(id);
        setDiagnosis(data);
        const detail = getDiseaseDetail(data.predictedDisease);
        setDiseaseDetail(detail);
      } catch (err: any) {
        console.error('Failed to load diagnosis detail:', err);
        setError(
          err.response?.data?.message ||
            err.message ||
            'Diagnosis record not found or you do not have permission to view it.'
        );
      } finally {
        setLoading(false);
      }
    };
    fetchDetail();
  }, [id]);

  const handleDeleteRecord = async () => {
    const recordId = diagnosis?.id || diagnosis?.diagnosisId || id;
    if (!recordId) return;

    setIsDeleting(true);
    try {
      await deleteDiagnosis(recordId);
      showToast('Scan history record deleted from database.', 'success');
      navigate('/recent-scans');
    } catch (err: any) {
      console.error('Failed to delete diagnosis:', err);
      showToast(
        err.response?.data?.message || err.message || 'Failed to delete diagnosis record.',
        'error'
      );
      setIsDeleting(false);
    }
  };

  const handleGenerateAi = async () => {
    if (!diagnosis || !diseaseDetail) return;
    setLoadingAi(true);
    setActiveTab('aiPlan');

    const apiKey = getStoredGeminiKey();
    const rawConf = diagnosis.confidenceScore ?? diagnosis.confidence ?? 0.92;
    const confStr = (rawConf > 1 ? rawConf : rawConf * 100).toFixed(1);

    try {
      if (apiKey) {
        const report = await generateGeminiAgronomistReport(
          diagnosis.cropType,
          diseaseDetail.displayName,
          confStr,
          apiKey
        );
        setAiReport(report);
      } else {
        const fallback = `
🌿 CEYGREEN AGRONOMIST RECOVERY PROTOCOL
================================================================================
Target Crop        : ${diagnosis.cropType}
Identified Disease : ${diseaseDetail.displayName} (${diseaseDetail.scientificName})
Severity Level     : ${diseaseDetail.severity}
Confidence Score   : ${confStr}%

1. IMMEDIATE FIELD ACTIONS:
--------------------------------------------------------------------------------
• Isolate infected crops: ${diseaseDetail.preventionAndQuarantine.quarantineAction}
• Pruning protocol: ${diseaseDetail.preventionAndQuarantine.sanitation.join(' ')}
• Airflow: ${diseaseDetail.preventionAndQuarantine.airflowAndSpacing}

2. CLIMATE ADJUSTMENTS:
--------------------------------------------------------------------------------
• Safe Temperature: ${diseaseDetail.microclimate.temperatureRange}
• Critical Humidity: Keep below ${diseaseDetail.microclimate.criticalHumidity}

3. SPREAD & TRANSMISSION:
--------------------------------------------------------------------------------
• Vectors: ${diseaseDetail.etiology.transmissionVectors.join(', ')}
• Host Inoculum: ${diseaseDetail.etiology.inoculumSource}
================================================================================
Generated by CeyGreen Plant Pathology AI
        `.trim();
        setAiReport(fallback);
      }
    } catch {
      setAiReport('Failed to generate AI consultation report. Please try again.');
    } finally {
      setLoadingAi(false);
    }
  };

  const handleCopy = () => {
    if (aiReport) {
      navigator.clipboard.writeText(aiReport);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  if (loading) {
    return (
      <div className="scan-detail-page">
        <div className="detail-skeleton">
          <div className="skeleton-line w-25 mb-4" />
          <div className="detail-layout">
            <div className="skeleton-image-box" />
            <div className="skeleton-info-box">
              <div className="skeleton-line w-50" />
              <div className="skeleton-line w-75" />
              <div className="skeleton-line w-100" />
            </div>
          </div>
        </div>
      </div>
    );
  }

  if (error || !diagnosis) {
    return (
      <div className="scan-detail-page">
        <div className="detail-error-card">
          <div className="error-icon-box">✕</div>
          <h2>Diagnosis Not Found</h2>
          <p>{error || 'The requested diagnosis record could not be located.'}</p>
          <Link to="/recent-scans" className="back-link-btn">
            ← Back to Scan History
          </Link>
        </div>
      </div>
    );
  }

  const rawConf = diagnosis.confidenceScore ?? diagnosis.confidence ?? 0.92;
  const confValue = rawConf > 1 ? rawConf : rawConf * 100;
  const confFormatted = confValue.toFixed(1);
  const isHealthy = diagnosis.predictedDisease?.toLowerCase().includes('healthy');
  const imageUrl = resolveDiagnosisImageUrl(diagnosis.imageUrl);

  return (
    <div className="scan-detail-page">
      {/* Top Breadcrumb Navigation */}
      <nav className="detail-breadcrumb">
        <div className="detail-breadcrumb-left">
          <Link to="/recent-scans" className="breadcrumb-back">
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
              <path d="M19 12H5M12 19l-7-7 7-7" />
            </svg>
            <span>Back to Scan History</span>
          </Link>
          <span className="breadcrumb-sep">/</span>
          <span className="breadcrumb-current">Scan #{diagnosis.id || diagnosis.diagnosisId || id}</span>
        </div>

        <button
          type="button"
          className="detail-delete-btn"
          onClick={() => setShowDeleteModal(true)}
          title="Delete this diagnosis scan"
        >
          <IconTrash size={16} />
          <span>Delete Record</span>
        </button>
      </nav>

      {/* Main Two-Column Layout */}
      <div className="detail-layout">
        {/* Left Column: Visual Media Card */}
        <div className="detail-media-column">
          <div className="detail-media-card">
            <div className="detail-img-wrap">
              <img
                src={imageUrl}
                alt={`${diagnosis.cropType} leaf`}
                className="detail-main-img"
                onError={(e) => {
                  (e.target as HTMLImageElement).src = '/dashboard/greenhouse.jpg';
                }}
              />
              <div className="detail-img-tag">
                <span>{diagnosis.cropType}</span>
              </div>
            </div>

            <div className="detail-media-meta">
              <div className="meta-row">
                <span className="meta-label">Diagnosis ID</span>
                <span className="meta-value font-mono">
                  {diagnosis.id || diagnosis.diagnosisId || id}
                </span>
              </div>
              <div className="meta-row">
                <span className="meta-label">Date Scanned</span>
                <span className="meta-value">
                  {diagnosis.timestamp || diagnosis.createdAt
                    ? new Date(diagnosis.timestamp || diagnosis.createdAt!).toLocaleString()
                    : 'Recent'}
                </span>
              </div>
              <div className="meta-row">
                <span className="meta-label">Pathogen Classification</span>
                <span className="meta-value font-semibold">
                  {diseaseDetail?.etiology.pathogenType || 'Vegetative Scan'}
                </span>
              </div>
            </div>
          </div>
        </div>

        {/* Right Column: Pathology & Action Plan */}
        <div className="detail-info-column">
          {/* Header Banner */}
          <div className="detail-header-card">
            <div className="detail-status-row">
              <span className={`pill-badge ${isHealthy ? 'healthy' : 'high'}`}>
                {isHealthy ? 'Healthy Foliage' : `${diseaseDetail?.severity || 'Diagnosed'} Risk`}
              </span>
              <span className="detail-crop-label">{diagnosis.cropType} Analysis</span>
            </div>

            <h1 className="detail-disease-title">
              {diseaseDetail ? diseaseDetail.displayName : diagnosis.predictedDisease}
            </h1>
            {diseaseDetail && (
              <p className="detail-scientific-name">
                Scientific Taxon: <em>{diseaseDetail.scientificName}</em>
              </p>
            )}

            {/* Confidence Meter */}
            <div className="detail-confidence-box">
              <div className="conf-header">
                <span>AI Model Confidence</span>
                <strong className="conf-score">{confFormatted}%</strong>
              </div>
              <div className="conf-bar-track">
                <div
                  className={`conf-bar-fill ${isHealthy ? 'healthy-fill' : 'disease-fill'}`}
                  style={{ width: `${Math.min(100, Math.max(10, confValue))}%` }}
                />
              </div>
            </div>
          </div>

          {/* Navigation Tabs */}
          <div className="detail-tabs-bar">
            <button
              type="button"
              className={`detail-tab ${activeTab === 'overview' ? 'active' : ''}`}
              onClick={() => setActiveTab('overview')}
            >
              Overview & Symptoms
            </button>
            <button
              type="button"
              className={`detail-tab ${activeTab === 'pathology' ? 'active' : ''}`}
              onClick={() => setActiveTab('pathology')}
            >
              Pathology & Vector
            </button>
            <button
              type="button"
              className={`detail-tab ${activeTab === 'treatment' ? 'active' : ''}`}
              onClick={() => setActiveTab('treatment')}
            >
              Quarantine & Sanitation
            </button>
            <button
              type="button"
              className={`detail-tab ${activeTab === 'aiPlan' ? 'active' : ''}`}
              onClick={() => {
                setActiveTab('aiPlan');
                if (!aiReport) handleGenerateAi();
              }}
            >
              AI Recovery Plan
            </button>
          </div>

          {/* Tab Content Cards */}
          <div className="detail-tab-content">
            {activeTab === 'overview' && diseaseDetail && (
              <div className="tab-pane">
                <h3 className="section-title">Diagnostic Characteristics</h3>
                <div className="symptoms-list">
                  {diseaseDetail.symptoms.leafMarkers.map((marker: string, i: number) => (
                    <div key={i} className="symptom-item">
                      <span className="symptom-dot" />
                      <span>{marker}</span>
                    </div>
                  ))}
                </div>

                <div className="detail-card-grid mt-4">
                  <div className="info-mini-card">
                    <h4>Canopy Progression</h4>
                    <p>{diseaseDetail.symptoms.canopyProgression}</p>
                  </div>
                  <div className="info-mini-card">
                    <h4>Stem & Fruit Signs</h4>
                    <p>{diseaseDetail.symptoms.stemAndFruitSigns.join(', ')}</p>
                  </div>
                </div>
              </div>
            )}

            {activeTab === 'pathology' && diseaseDetail && (
              <div className="tab-pane">
                <h3 className="section-title">Pathogen & Environmental Drivers</h3>
                <div className="detail-card-grid">
                  <div className="info-mini-card">
                    <div className="mini-card-head">
                      <IconThermo size={18} />
                      <h4>Temperature Threshold</h4>
                    </div>
                    <p>{diseaseDetail.microclimate.temperatureRange}</p>
                  </div>
                  <div className="info-mini-card">
                    <div className="mini-card-head">
                      <IconDrop size={18} />
                      <h4>Critical Humidity</h4>
                    </div>
                    <p>{diseaseDetail.microclimate.criticalHumidity}</p>
                  </div>
                </div>

                <div className="info-mini-card mt-3">
                  <h4>Transmission Vectors</h4>
                  <p>{diseaseDetail.etiology.transmissionVectors.join(', ')}</p>
                </div>

                <div className="info-mini-card mt-3">
                  <h4>Primary Inoculum Source</h4>
                  <p>{diseaseDetail.etiology.inoculumSource}</p>
                </div>
              </div>
            )}

            {activeTab === 'treatment' && diseaseDetail && (
              <div className="tab-pane">
                <h3 className="section-title">Quarantine & Field Protocols</h3>
                <div className="quarantine-banner">
                  <IconShield size={22} />
                  <div>
                    <strong>Quarantine Action Required</strong>
                    <p>{diseaseDetail.preventionAndQuarantine.quarantineAction}</p>
                  </div>
                </div>

                <h4 className="subhead-title mt-4">Sanitation & Pruning Rules</h4>
                <ul className="action-bullets">
                  {diseaseDetail.preventionAndQuarantine.sanitation.map((rule, i) => (
                    <li key={i}>{rule}</li>
                  ))}
                </ul>

                <div className="detail-card-grid mt-4">
                  <div className="info-mini-card">
                    <h4>Airflow & Spacing</h4>
                    <p>{diseaseDetail.preventionAndQuarantine.airflowAndSpacing}</p>
                  </div>
                  <div className="info-mini-card">
                    <h4>Crop Rotation</h4>
                    <p>{diseaseDetail.preventionAndQuarantine.cropRotation}</p>
                  </div>
                </div>
              </div>
            )}

            {activeTab === 'aiPlan' && (
              <div className="tab-pane">
                <div className="ai-plan-head">
                  <div className="ai-badge">AI Agronomist Recovery Protocol</div>
                  {aiReport && (
                    <div className="ai-actions">
                      <button type="button" onClick={handleCopy} className="action-btn">
                        {copied ? '✓ Copied' : 'Copy Plan'}
                      </button>
                      <button type="button" onClick={() => window.print()} className="action-btn">
                        Print
                      </button>
                    </div>
                  )}
                </div>

                {loadingAi ? (
                  <div className="ai-loading-box">
                    <div className="ai-spinner" />
                    <p>Consulting CeyGreen AI Agronomist for custom recovery instructions...</p>
                  </div>
                ) : (
                  <pre className="ai-report-text">{aiReport}</pre>
                )}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Delete Confirmation Modal */}
      {showDeleteModal && (
        <div
          className="delete-modal-overlay"
          onClick={() => !isDeleting && setShowDeleteModal(false)}
          role="dialog"
          aria-modal="true"
        >
          <div className="delete-modal-card" onClick={(e) => e.stopPropagation()}>
            <div className="delete-modal-header">
              <div className="delete-warning-icon">
                <IconAlertTriangle size={24} />
              </div>
              <h3 className="delete-modal-title">Delete Diagnosis Record?</h3>
            </div>

            <div className="delete-modal-body">
              <p>
                Are you sure you want to permanently remove the diagnosis for{' '}
                <strong>{diagnosis.cropType}</strong> (
                {diseaseDetail?.displayName || diagnosis.predictedDisease})?
              </p>
              <p className="delete-modal-subtext">
                This will delete the diagnosis and associated image data from the database. You will be
                redirected to the scan archive.
              </p>
            </div>

            <div className="delete-modal-actions">
              <button
                type="button"
                className="delete-modal-cancel-btn"
                onClick={() => setShowDeleteModal(false)}
                disabled={isDeleting}
              >
                Cancel
              </button>
              <button
                type="button"
                className="delete-modal-confirm-btn"
                onClick={handleDeleteRecord}
                disabled={isDeleting}
              >
                {isDeleting ? (
                  <>
                    <span className="scan-card-delete-spinner" aria-hidden />
                    <span>Deleting...</span>
                  </>
                ) : (
                  <>
                    <IconTrash size={16} />
                    <span>Delete Record</span>
                  </>
                )}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

